version: '3.1'

services:
  orchestrator:
    build:
      dockerfile: orchestrator.Dockerfile
    ports:
      - "50051:50051"
  http-server:
    build:
      dockerfile: http_server.Dockerfile
    ports:
      - "5441:5441"
  agent:
    deploy:
      mode: replicated
      replicas: 1  # ЗДЕСЬ МОЖНО ИЗМЕНИТЬ КОЛИЧЕСТВО АГЕНТОВ
    build:
      dockerfile: agent.Dockerfile
  migrator:
    build:
      dockerfile: migrator.Dockerfile
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calc_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  postgres: