version: '3'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calc_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres: